algoritmo "areaquadrado"
// Função : Este programa solicita um valor e cula a área do quadrado
// Autor : Leonardo Teixeira da Silva
// Data : 01/03/2024
// Seção de Declarações 
var

areaQ: real
lado: real

inicio
// Entrada

escreva   ("Qual o lado do quadrado?")
leia(lado)

//Processamento
areaQ <- lado * lado

//Saída

escreva ("A área do quadrado é:", areaQ)

fimalgoritmo
